# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86ece22058529b4b0a76cf40be41b39cd589bbcb8be407139a3925c9c31c0782b8705e77acad7b59b77cd9be6b4a8023fd8c3e730a67dc5dd81c79ea48411292

test:
  secret_key_base: 54e17578a9ece2fb45be1d712a2ba9a8389143c19d82c9b6e985553d32272e076b9873f39638bc1734967420f50df4e5eaaf56f9d2b2f818d47f704c951df143

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
